### PR TITLE
added some code to use authelia groups

### PR DESCRIPTION
**Pull request by WilssoN93**
Hey, Even though i'm not a CSharp developer i took a stab at adding groups to the Jellyfin User since they are available in the response header from authelia /verify endpoint. 

Disclaimer: I was not sure how to build and test locally so it is likely this is not working as expected. 
But maybe this can give you an idea if you wanted to implement group management in the future :)

### CODE REVIEW

**Comment by nikarh** [comment]
Hey, thanks for the PR!

Before we go that route, I would like to check if its possible to offload group checking to Authelia itself by leveraging `access_control.rules.subject`. That would simplify the potential UI for this feature (because otherwise I'm not entirely sure how exactly should it be exposed)

**Comment by WilssoN93** [comment]
Hey, It dosnt seems to work for me, 
This is my rule
```
    - domain: "jelly.server.home"
      subject:
        - "group:jellyfinadmin"
        - "group:jellyfinuser"
      policy: one_factor
```
and is the same url as defined in plugin config

I can log in, but i dont get admin persmisson.
I would like to have a admin role defined that i can use to give admin permissions

**Comment by nikarh** [comment]
> Hey, It dosnt seems to work for me, This is my rule
> 
> ```
>     - domain: "jelly.server.home"
>       subject:
>         - "group:jellyfinadmin"
>         - "group:jellyfinuser"
>       policy: one_factor
> ```
> 
> and is the same url as defined in plugin config
> 
> I can log in, but i dont get admin persmisson. I would like to have a admin role defined that i can use to give admin permissions

Oh, got it. Then I have a couple of questions about how you see it.

- What happens if the group changes in Authelia? Should it actively manage users' admin permissions on log-in or not? If yes, that may be a problem for two reasons:
  - Some users may prefer managing admin permissions for Jellyfin outside of Authelia, and I'm not sure forcing that would be a good idea
  - In that scheme, user permission would get updated only on successful login, so it won't be updated for login with a PIN for instance
- If we update the admin role in Jellyfin on the login
  - How can I opt out of it?
  - Does it affect users that were not originally created by this plugin?
- What configuration options would there be besides a group user should have to get admin permissions?

Overall, I would propose the following (as the simplest solution):

- Admin permissions are given only if a user is created via this plugin.
- They are never updated. This would align with the fact that there are more permission-related options in Jellyfin, such as library accesses, parental control, etc, and they are not managed via Authelia
- The configuration flag is an optional field for the admin group. If this plugin creates a new user, the field is non-empty, and the user has this group, the user is created with admin permissions

**Comment by nikarh** [comment]
The other approach could be:

- The configuration flag is an optional field for the admin group. If it's left empty, the plugin does not manage admin permissions
- If the configuration field is non-empty, on every login, regardless of how the user was created we check if the user has the group. If the user has the group, admin permissions are enabled for the user. If the user doesn't have the group, admin permissions are taken away from the user

**Comment by nikarh** [comment]
> > The other approach could be:
> > 
> > * The configuration flag is an optional field for the admin group. If it's left empty, the plugin does not manage admin permissions
> > * If the configuration field is non-empty, on every login, regardless of how the user was created we check if the user has the group. If the user has the group, admin permissions are enabled for the user. If the user doesn't have the group, admin permissions are taken away from the user
> 
> Yeah that was my thought maybe have a flag that if true (default false) enables permission management through authelia. And if not its managed in jellyfin. That way you can opt-in if you want to use authelia groups. :)

Hey, I did exactly that in this commit - 02ce3113b5871febde8b7ea48fd9d24f9595d728. Skipped the bool flag, since making the input optional and having a description of its behavior IMHO is sufficient. I've used some of the ideas from your draft also (e.g. removing redundant HTTP call and extracting full name from `/api/verify`. Thanks for your effort and for sharing your ideas!

This change is now released as a new version of the plugin

**Comment by WilssoN93** [comment]
Looks good! :) seems to work. Thanks!

**Pull request closed without merging**
